namespace Forge.Api.Contracts;

public sealed record SystemCapabilitiesResponse(
    string AiMode,
    string ClarificationProvider,
    string ClarificationModel,
    string ReasoningEffort,
    bool ClarificationConfigured,
    string PlanningProvider,
    string PlanningModel,
    string PlanningReasoningEffort,
    bool PlanningConfigured,
    string ImplementationProvider,
    string? ImplementationModel,
    string? ImplementationReasoningEffort,
    bool ImplementationConfigured,
    bool AiConfigured,
    bool RepositoryInspectionAvailable,
    bool PlanningAvailable,
    bool TargetModificationAvailable,
    bool ImplementationApprovalAvailable,
    bool ImplementationCorrectionAvailable,
    bool ValidationAvailable,
    bool ReviewAvailable,
    bool PullRequestCreationAvailable);
