namespace Forge.Core;

public enum WorkflowStatus
{
    Draft,
    Clarifying,
    RequirementSummaryReady,
    AwaitingRequirementApproval,
    ReadyForPlanning,
    Planning,
    AwaitingPlanApproval,
    PlanApproved,
    Implementing,
    AwaitingImplementationReview,
    ImplementationApproved,
    VerificationPlanning,
    AwaitingManualVerification,
    ManualVerificationFailed,
    FailureAnalysisPending,
    FailureAnalysisRecoveryRequired,
    AwaitingFailureResolution,
    AwaitingCorrectionApproval,
    CorrectionApproved,
    ImplementingCorrection,
    CorrectionRecoveryRequired,
    ReadyForDelivery,
    AwaitingDeliveryApproval,
    Delivering,
    PullRequestCreated,
    DeliveryRecoveryRequired,
    Validating,
    Reviewing,
    Completed,
    Failed
}
